export default {
    toolbar: {
      save: '存檔',
      download: '下載',
      undo: '復原',
      redo: '取消復原',
      print: '列印',
      paintformat: '複製格式',
      clearformat: '清除格式',
      format: '格式',
      fontName: '字型',
      fontSize: '字型大小',
      fontBold: '粗體',
      fontItalic: '斜體',
      underline: '底線',
      strike: '删除线',
      color: '字型色彩',
      bgcolor: '填滿色彩',
      border: '框線',
      merge: '跨欄置中',
      align: '水平置中',
      valign: '垂直置中',
      textwrap: '自动换行',
      freeze: '凍結視窗',
      autofilter: '篩選',
      formula: '自動加總',
      upDateload: '上傳檔案',
      percent:'百分比',
      more: '更多',
    },
    contextmenu: {
      copy: '複製',
      cut: '剪下',
      paste: '貼上',
      pasteValue: '貼上(文字)',
      pasteFormat: '貼上(格式)',
      hide: '隱藏',
      insertRow: '插入一行',
      insertColumn: '插入一列',
      deleteSheet: '删除',
      deleteRow: '删除一行',
      deleteColumn: '删除一列',
      deleteCell: '删除',
      deleteCellText: '移除',
      validation: '資料校正',
      cellprintable: '可列印',
      cellnonprintable: '不可列印',
      celleditable: '可編輯',
      cellnoneditable: '不可编辑',
      UpDateload:'傳檔',
    },
    print: {
      size: '紙張大小',
      orientation: '方向',
      orientations: ['横向', '直向'],
    },
    format: {
      normal: '正常',
      text: '文字',
      number: '數字',
      percent: '百分比',
      rmb: '人民幣',
      usd: '美元',
      eur: '歐元',
      date: '短日期',
      time: '時間',
      datetime: '長日期',
      duration: '期間',
    },
    formula: {
      sum: '加總和',
      average: '平均值',
      max: '求最大值',
      min: '求最小值',
      concat: '字符連結',
      _if: '條件判斷',
      and: '和',
      or: '或',
    },
    validation: {
      required: '此值必填',
      notMatch: '此值不匹配驗證規則',
      between: '此值應在 {} 和 {} 之間',
      notBetween: '此值不應在 {} 和 {} 之間',
      notIn: '此值不在列表中',
      equal: '此值應該等於 {}',
      notEqual: '此值不應該等於 {}',
      lessThan: '此值應該小於 {}',
      lessThanEqual: '此值應該小於等於 {}',
      greaterThan: '此值應該大於 {}',
      greaterThanEqual: '此值應該大於等於 {}',
    },
    error: {
      pasteForMergedCell: '無法對合併儲存格進行操作',
    },
    calendar: {
      weeks: ['日', '一', '二', '三', '四', '五', '六'],
      months: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
    },
    button: {
      next: '下一步',
      cancel: '取消',
      remove: '移除',
      save: '儲存',
      ok: '確認',
    },
    sort: {
      desc: '降序',
      asc: '升序',
    },
    filter: {
      empty: '空白',
    },
    dataValidation: {
      mode: '模組',
      range: '單元區間',
      criteria: '條件',
      modeType: {
        cell: '儲存格',
        column: '列模組',
        row: '行模祖',
      },
      type: {
        list: '清單',
        number: '數字',
        date: '日期',
        phone: '手機號碼',
        email: '電子郵件',
      },
      operator: {
        be: '在區間',
        nbe: '不在區間',
        lt: '小於',
        lte: '小於等於',
        gt: '大於',
        gte: '大於等於',
        eq: '等於',
        neq: '不等於',
      },
    },
  };
  